---
ID: "132af3ba-6bcf-459b-9093-eda60ceadb03"
Parent: "d1ee6600-cad1-4c82-8c02-679564e5826e"
Template: "d1ee6600-cad1-4c82-8c02-679564e5826e"
Path: /sitecore/templates/Project/solo/Components/Highlights/Rendering Parameters/Highlights Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "dc581da2-9f5c-473a-8bf9-083c229c517c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251211T094712Z
