---
ID: "680fbdf3-58de-4d42-b8ee-03e5f020effd"
Parent: "9576af60-6a44-4a79-8945-12cb88647c25"
Template: "9576af60-6a44-4a79-8945-12cb88647c25"
Path: /sitecore/templates/Project/solo/Components/Highlights/Highlights Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {8F6B5AB9-1134-43B0-A0C3-8C5B1D0DCA6D}
    {9576AF60-6A44-4A79-8945-12CB88647C25}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "da68264b-a3d9-4f99-b1bc-ec893f85d160"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b7bf991d-5bce-4406-bba6-aae82bf9c110"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251211T094716Z
