---
ID: "3de41bfe-9b5a-49cd-8022-f5a888dc4453"
Parent: "cd225f02-203e-4052-91c5-ce4b81bda4b1"
Template: "ab86861a-6030-46c5-b394-e8f99e8b87db"
Path: /sitecore/templates/Project/solo/JSS Settings
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Office/32x32/gearwheels.png
- ID: "12c33f3f-86c5-43a5-aeb4-5598cec45116"
  Hint: __Base template
  Value: |
    {EC848505-D30C-4BDC-A0AA-7CC9D320085E}
    {CBC14160-BED0-4AA2-9387-4C13179205B9}
    {A7228B46-610D-4A17-9F61-649F3A30AAAE}
    {6175F4C7-F87F-4F7F-928E-4C5CA5DFFAF4}
    {2AF2DC09-057F-48C2-A9F4-9779ADF83659}
    {30869218-C3AD-40F9-BCFF-6837127ECD8F}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "56fbfd19-c936-4d40-a52e-054b42c35311"
- ID: "f7d48a55-2158-4f02-9356-756654404f73"
  Hint: __Standard values
  Value: "{9D222525-C9A5-4DB0-BB23-5DE59B828CF5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251209T141006Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "694d8b28-088d-4a9a-8164-b408dc34fb78"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251209T141011Z
