---
ID: "6a933b30-9a69-4ae2-b397-a57d66a5f7d9"
Parent: "56d71726-051c-4acb-9d1e-5ef048515e71"
Template: "56d71726-051c-4acb-9d1e-5ef048515e71"
Path: /sitecore/templates/Project/solo/Partial Design Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {56D71726-051C-4ACB-9D1E-5EF048515E71}
    {FD2059FD-6043-4DFE-8C04-E2437CE87634}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "117e3295-a909-4667-b2d2-911089d01540"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251209T141003Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2bfe6892-11d4-40fc-a9eb-b27bcb4eecd7"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251209T141009Z
