---
ID: "fbfcf620-4082-463e-a306-8416c8c6510f"
Parent: "659a0167-26cb-43b5-be6c-9ea9d7767521"
Template: "659a0167-26cb-43b5-be6c-9ea9d7767521"
Path: /sitecore/templates/Project/solo/Components/News/Rendering Parameters/News Card Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4dedc517-335b-4d0c-93f3-5f8f9c1e9ca7"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251210T130711Z
