---
ID: "f8decc29-69f7-4cab-9c6d-c63d1d2c4b7d"
Parent: "19ba4928-23eb-4fe4-8d64-926b0deac834"
Template: "19ba4928-23eb-4fe4-8d64-926b0deac834"
Path: /sitecore/templates/Project/solo/Article Page/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{C14B6289-8AC2-439C-9E5B-40DE9F820C3F}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "0e622e3e-7ded-4e69-bb50-f99f3de53f60"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251209T141004Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1ef7fb3a-aa00-46af-aa1a-625078a7ad8c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251212T144000Z
