---
ID: "615d4479-45f0-483e-83d3-1b1529341d7b"
Parent: "f659d04c-1a26-41a1-91af-6f7ba2313f28"
Template: "f659d04c-1a26-41a1-91af-6f7ba2313f28"
Path: /sitecore/templates/Project/solo/Components/Highlights/Rendering Parameters/HighlightTeaser Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "984bed7b-56fa-4cfd-8281-ba86ae1ed8ed"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251219T073131Z
