---
ID: "1c17fea4-0310-4e7d-b6ac-dd7902beb6b2"
Parent: "9e9b0735-497f-4fa6-be6e-00e9e0036713"
Template: "9e9b0735-497f-4fa6-be6e-00e9e0036713"
Path: /sitecore/templates/Project/solo/Components/Events/Event Details Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {E1F31EA6-8A94-4EF5-8BCB-CF31D3780CA7}
    {9E9B0735-497F-4FA6-BE6E-00E9E0036713}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "ccebff05-0e00-4ff3-998b-e67e371a2f02"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2725bba7-297d-4560-adc4-4d60b846134e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251212T150744Z
