---
ID: "5dc3326a-4b7a-48fc-b23b-38dbf726ea9d"
Parent: "5542dd64-fa4b-4ad0-b58f-82749bca7fed"
Template: "5542dd64-fa4b-4ad0-b58f-82749bca7fed"
Path: /sitecore/templates/Project/solo/Components/Brands/Brand List Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {4DCAAC4E-56A1-4125-BC9F-66DD3AEFC908}
    {5542DD64-FA4B-4AD0-B58F-82749BCA7FED}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "e77d9462-f85e-41b2-bccc-d029608af794"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d133a260-1fdb-4001-9853-76050aa04da9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251210T124355Z
