---
ID: "ec02129a-23c5-486b-92da-067a7bcfac93"
Parent: "dcaf4870-1e33-472a-b889-216e3bfef8ae"
Template: "dcaf4870-1e33-472a-b889-216e3bfef8ae"
Path: /sitecore/templates/Project/solo/Components/Newsletter/Newsletter Signup Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {CB6DBEAA-A9B8-43F1-82C7-57EE0CE930C4}
    {DCAF4870-1E33-472A-B889-216E3BFEF8AE}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "1422ac82-e65e-43ad-abfc-c428b707718b"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "45e685a2-05ff-480f-bea1-67487966feab"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251211T123102Z
