---
ID: "5f8c2377-6f7b-4f96-8f7d-fedb2f201d6c"
Parent: "d689af56-3fa3-4525-b912-42c827344aa9"
Template: "d689af56-3fa3-4525-b912-42c827344aa9"
Path: /sitecore/templates/Project/solo/Components/Global/Header Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {CCF3639B-CC3A-4BB8-9E4B-C39EF303D75B}
    {D689AF56-3FA3-4525-B912-42C827344AA9}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "5b94774f-6a6b-4eb5-8ca2-c488f6bf1f25"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d08903a4-faa2-4e3f-89b6-944031f6b2a3"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251209T154817Z
