---
ID: "2ac0d0b2-398e-4afb-ae25-b73aa9d9034d"
Parent: "f1967c1d-8d15-436c-9f2f-79748b8c1453"
Template: "f1967c1d-8d15-436c-9f2f-79748b8c1453"
Path: /sitecore/templates/Project/solo/Components/Media/Rendering Parameters/ImageHotspot Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ecb015a5-46c3-40a4-bb71-eb5a4f7ee006"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260206T163032Z
