---
ID: "4e7e02fb-ad22-4cce-ab23-8c4bf488db69"
Parent: "734e06dd-efb6-4bcb-8b7f-8e1fb581fe38"
Template: "734e06dd-efb6-4bcb-8b7f-8e1fb581fe38"
Path: /sitecore/templates/Project/solo/Components/Persons/Rendering Parameters/AuthorTeaser Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c85d55c0-a127-45db-bf40-ef2ba8ca9992"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251217T141236Z
