---
ID: "9fb24ced-52ae-4ea5-a765-ad170e3b8300"
Parent: "af7324db-5a77-4457-b561-892dedaa497b"
Template: "af7324db-5a77-4457-b561-892dedaa497b"
Path: /sitecore/templates/Project/solo/Components/News/NewsDetailsContent Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {38ECBCCD-B932-417C-B78C-AD1F03DE54B2}
    {AF7324DB-5A77-4457-B561-892DEDAA497B}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "ae33097f-0c2e-40d3-947f-4494c4b86f50"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "45a12f61-e59c-4e94-897a-315a14ede72f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251217T133002Z
