---
ID: "34a18936-418b-4a8c-9b68-213c78e58f5e"
Parent: "e5e11a3b-98c8-41cc-9795-7296bc2e1786"
Template: "e5e11a3b-98c8-41cc-9795-7296bc2e1786"
Path: /sitecore/templates/Project/solo/Components/Media/Image Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {AC142619-618E-4582-ADE4-BC85AA13ECB7}
    {E5E11A3B-98C8-41CC-9795-7296BC2E1786}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "120e4859-8817-4f28-91ec-9d4867ad7aca"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "145fcbe6-5676-4564-a140-047c55c099e0"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260224T104645Z
