---
ID: "7accb2d2-ca74-496f-9f96-2d6abcfc7147"
Parent: "f180cb22-11d8-48ec-be94-f527383abc74"
Template: "f180cb22-11d8-48ec-be94-f527383abc74"
Path: /sitecore/templates/Project/solo/Components/Faq/Elements/Faq Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {F180CB22-11D8-48EC-BE94-F527383ABC74}
    {97857543-BD09-4C12-9A09-74252529883F}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "a95bc448-a907-4287-9efd-694056492364"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "13a51435-99cc-41d2-8f21-c123409124e4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260103T174018Z
