---
ID: "a0395908-020b-4eee-a3c6-0c09ba94b873"
Parent: "fbc8a89c-ad32-4adb-b3ca-3f200d3f99c8"
Template: "fbc8a89c-ad32-4adb-b3ca-3f200d3f99c8"
Path: /sitecore/templates/Project/solo/Components/Media/Youtube Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {82D9782C-594E-4C5F-BD8A-F0496FB613C4}
    {FBC8A89C-AD32-4ADB-B3CA-3F200D3F99C8}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "31cdf7b7-423d-4f71-b9fe-ccc9bd4eeda6"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6f597d44-d8bb-47ad-addf-0d77df6d6384"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260224T104718Z
