---
ID: "eacf62b6-7a7b-4d52-9a86-00e1ee74cdc9"
Parent: "5d483633-0855-4648-8bba-dfcdcdaf2184"
Template: "5d483633-0855-4648-8bba-dfcdcdaf2184"
Path: /sitecore/templates/Project/solo/Components/Content/Tagcloud Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {05310667-C1F0-4647-927D-D51C625A9A90}
    {5D483633-0855-4648-8BBA-DFCDCDAF2184}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "c8c7be35-093e-47bb-98a6-9327c357d735"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c8f0ba09-1a84-4ba1-8d6c-276160cb9489"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260101T162738Z
