---
ID: "a3312300-2628-48b2-b40a-d4add7381019"
Parent: "0d1bb76b-844f-42f9-a325-7ed811d3b267"
Template: "0d1bb76b-844f-42f9-a325-7ed811d3b267"
Path: /sitecore/templates/Project/solo/Components/Heroes/Rendering Parameters/HeroBanner Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ee43cbad-7fb6-495d-94ba-8f415c0216cc"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251210T121355Z
