---
ID: "1c348935-10c2-48f8-8f61-00e8d177eb33"
Parent: "3fcb1615-7c97-40ee-aed3-8710b289908e"
Template: "3fcb1615-7c97-40ee-aed3-8710b289908e"
Path: /sitecore/templates/Project/solo/Components/Newsletter/Rendering Parameters/Newsletter Signup Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "825abae7-8710-4c3d-8464-bf8a1b4e8571"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251211T123057Z
