---
ID: "4eabe44d-a50b-449e-9aaa-c42adedc0d82"
Parent: "7e9b34bb-0e90-42d7-a6e7-2d3d9833c15c"
Template: "7e9b34bb-0e90-42d7-a6e7-2d3d9833c15c"
Path: /sitecore/templates/Project/solo/Components/News/Rendering Parameters/News RelatedNews Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9e86adbb-7719-49b5-b0e6-3bcf1aa72036"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251217T145350Z
