---
ID: "667c895f-40e9-4a55-ad2a-62b7422f75e2"
Parent: "7feed9c7-ed63-42e1-af69-a856cd2702f5"
Template: "7feed9c7-ed63-42e1-af69-a856cd2702f5"
Path: /sitecore/templates/Project/solo/Components/Global/Rendering Parameters/Footer Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "075b5fcc-57f0-46e3-98dc-a59c88cf5740"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251209T155335Z
