---
ID: "dc76cff4-271d-4d30-bd64-203cbdc3ea83"
Parent: "02d3bf45-b86c-4826-859c-7169f40f6dd7"
Template: "02d3bf45-b86c-4826-859c-7169f40f6dd7"
Path: /sitecore/templates/Project/solo/Components/Media/Image List Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{8BD15F11-A799-4EDB-B970-4E8BDA3C3699}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "d298f92a-3f5a-4f74-b0aa-f1944f000eaf"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T061559Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "85b79c06-a16d-42fa-b7ac-64c77f419d76"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251216T142328Z
