---
ID: "e315021b-9a96-4d0b-ac92-d349cff7df24"
Parent: "44eadf66-53c0-4384-960b-81691d619c81"
Template: "44eadf66-53c0-4384-960b-81691d619c81"
Path: /sitecore/templates/Project/solo/Article Root/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {C14B6289-8AC2-439C-9E5B-40DE9F820C3F}
    {FA3F23AF-7950-4FC6-88F8-A9773F61E25B}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "4c611c06-748e-42d1-87bb-82ec3cace7e9"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251209T141004Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "494a7c5e-36ea-4cda-85a2-0ee2475baf3c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251218T064122Z
