---
ID: "6be178ee-6bf6-4cd8-abe1-e0e2a24b3876"
Parent: "6c515802-f43d-4f45-b4e5-a5aafc5dbd76"
Template: "6c515802-f43d-4f45-b4e5-a5aafc5dbd76"
Path: /sitecore/templates/Project/solo/Page/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {6C515802-F43D-4F45-B4E5-A5AAFC5DBD76}
    {C14B6289-8AC2-439C-9E5B-40DE9F820C3F}
    {44EADF66-53C0-4384-960B-81691D619C81}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "4a485f5e-194b-4306-84cd-cb1ac9ff9096"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "1caf1c52-fe82-4a76-8f79-269ec2b84c52"
      Hint: Title
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251209T141004Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "295a1f18-a17a-43f3-abb9-764251f1134b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251212T144100Z
