---
ID: "74c76a34-5af5-4ad8-90df-27cc7933f455"
Parent: "5dacb9d3-8ee9-4a00-81ae-017563e74b94"
Template: "5dacb9d3-8ee9-4a00-81ae-017563e74b94"
Path: /sitecore/templates/Project/solo/Components/Content/Rendering Parameters/Text Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fffc19e5-7ed2-456e-8072-460b813c5271"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251219T132216Z
