---
ID: "91b357d6-da5d-496e-b049-30d2848ac40f"
Parent: "02a714c8-25b3-4ebf-a393-77dd48f5add3"
Template: "02a714c8-25b3-4ebf-a393-77dd48f5add3"
Path: /sitecore/templates/Project/solo/Components/Media/Rendering Parameters/Image Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "08c83e36-f07d-44ba-9115-3ef3426aabf4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260224T104640Z
