---
ID: "18a36300-ce3d-4529-92d0-d19cc017e801"
Parent: "758c5db2-2c19-4f6a-ae99-affaef9f5984"
Template: "758c5db2-2c19-4f6a-ae99-affaef9f5984"
Path: /sitecore/templates/Project/solo/Components/News/Rendering Parameters/News List Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a029f222-3e23-44e8-8ddc-424c48c04a24"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251210T143434Z
