---
ID: "7ca819b4-de99-4d8a-a3e8-fc3bacc6239c"
Parent: "bc21877f-2534-4732-9740-647095b5e202"
Template: "bc21877f-2534-4732-9740-647095b5e202"
Path: /sitecore/templates/Project/solo/Partial Designs/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {56D71726-051C-4ACB-9D1E-5EF048515E71}
    {FD2059FD-6043-4DFE-8C04-E2437CE87634}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "cd9fae22-5af3-41d2-bafa-03cc4d068cc3"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251209T141004Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "50e3225a-5d1e-4eed-bf1d-c0e5598758bb"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251209T141009Z
