---
ID: "060674ed-f776-46bf-bd40-13675a367386"
Parent: "71c2489d-76d0-4892-a831-886bef196caa"
Template: "71c2489d-76d0-4892-a831-886bef196caa"
Path: /sitecore/templates/Project/solo/Components/Brands/Rendering Parameters/Brand List Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1ea6daed-dea1-4a63-9724-5a1125b0be39"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251210T124351Z
