---
ID: "7102842f-58f8-4c6e-b00d-ade0461e751a"
Parent: "c6988798-8ca5-4ab9-aa6b-0f4f6c2ad41f"
Template: "c6988798-8ca5-4ab9-aa6b-0f4f6c2ad41f"
Path: /sitecore/templates/Project/solo/Components/News/Rendering Parameters/News KeyTakeaways Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "66c20a5a-9eec-45e3-8148-8e9252be7462"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251217T143618Z
