---
ID: "b4521aee-3158-4b10-b6a9-cf88d5031d7c"
Parent: "2420c2a0-9360-47eb-979d-159a2a733b15"
Template: "2420c2a0-9360-47eb-979d-159a2a733b15"
Path: /sitecore/templates/Project/solo/Components/Content/TagElement/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "245bdf51-4d4e-4f2c-8843-7838cbe41249"
      Hint: Name
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T164138Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2e7cd923-7faa-490c-8b4a-bf05b08428f4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260101T164143Z
